[package]
name = "kasplex-reth-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "kasplex-reth"
path = "src/main.rs"

[dependencies]
kasplex-reth-cli = { path = "../../crates/cli" }
kasplex-reth-node = { path = "../../crates/node" }
kasplex-reth-rpc = { path = "../../crates/rpc" }
reth = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.10.1", package = "reth" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.10.1", package = "reth-cli-util" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.10.1", package = "reth-rpc" }
tracing = { workspace = true }




