[package]
name = "kasplex-reth-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "kasplex-reth"
path = "src/main.rs"

[dependencies]
kasplex-reth-cli = { path = "../../crates/cli" }
kasplex-reth-node = { path = "../../crates/node" }
kasplex-reth-rpc = { path = "../../crates/rpc" }
reth = { workspace = true }
reth-cli-util = { workspace = true }
reth-rpc = { workspace = true }
tracing = { workspace = true }




